### PR TITLE
refactor: several util functions

### PR DESCRIPTION
**Pull request by laquasicinque**

### CODE REVIEW

**Comment by MrPrimate** [comment]
When running the Item munch using this branch rebased onto master gets the following error:

```
logger.js:62 DDB Importer | ERR > TypeError: Cannot read property 'rawSign' of undefined
    at Object.parseDiceString (http://localhost:30000/modules/ddb-importer/src/utils.js:464:9)
    at getDamage (http://localhost:30000/modules/ddb-importer/src/parser/inventory/weapon.js:224:13)
    at parseWeapon (http://localhost:30000/modules/ddb-importer/src/parser/inventory/weapon.js:420:7)
    at parseItem (http://localhost:30000/modules/ddb-importer/src/parser/inventory/index.js:296:20)
    at getInventory (http://localhost:30000/modules/ddb-importer/src/parser/inventory/index.js:425:34)
    at generateImportItems (http://localhost:30000/modules/ddb-importer/src/muncher/items.js:69:21)
    at http://localhost:30000/modules/ddb-importer/src/muncher/items.js:112:24
log @ logger.js:62
error @ logger.js:82
parseItem @ index.js:345
getInventory @ index.js:425
generateImportItems @ items.js:69
(anonymous) @ items.js:112
Promise.then (async)
(anonymous) @ items.js:112
getItemData @ items.js:86
parseItems @ items.js:143
async function (async)
parseItems @ items.js:142
parseItems @ ddb.js:250
(anonymous) @ ddb.js:106
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
logger.js:62 DDB Importer | ERR > TypeError: Cannot read property 'properties' of undefined
log @ logger.js:62
error @ logger.js:82
parseItems @ ddb.js:255
async function (async)
parseItems @ ddb.js:250
(anonymous) @ ddb.js:106
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
logger.js:62 DDB Importer | ERR > TypeError: Cannot read property 'properties' of undefined
    at enrichFlags (http://localhost:30000/modules/ddb-importer/src/parser/inventory/index.js:370:19)
    at getInventory (http://localhost:30000/modules/ddb-importer/src/parser/inventory/index.js:427:5)
    at generateImportItems (http://localhost:30000/modules/ddb-importer/src/muncher/items.js:69:21)
    at http://localhost:30000/modules/ddb-importer/src/muncher/items.js:112:24
```

**Comment by laquasicinque** [comment]
Sure, I'll take a look at what went wrong 👀

**Comment by laquasicinque** [comment]
fml, I missed an `s` on `groups` which is what tripped up, I was a little confused because I was trying to basically keep the output the same (and most of the logic) especially for the dice parsing. Are there any particular items that I should use to double check the dice parsing hasn't been borked?

**Comment by MrPrimate** [comment]
👍🏻

**Pull request merged**
